---
# to generate this secret use the command
# cp aws.env.sample aws.env
# oc create secret generic cad-aws-credentials -n configuration-anomaly-detection --from-env-file=aws.env --dry-run -oyaml > task-cad-checks-secrets-aws.yaml
# CAD_AWS_CSS_JUMPROLE and CAD_AWS_SUPPORT_JUMPROLE are used for internal auth flow (working without that is possible with this flag: //TODO link to card that does this)
apiVersion: v1
kind: Secret
metadata:
  name: cad-aws-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: CHANGEME
  AWS_DEFAULT_REGION: CHANGEME
  AWS_SECRET_ACCESS_KEY: CHANGEME
  AWS_SESSION_TOKEN: CHANGEME # not required
  CAD_AWS_CSS_JUMPROLE: CHANGEME 
  CAD_AWS_SUPPORT_JUMPROLE: CHANGEME