---
# to generate this secret use the command
# oc create secret generic cad-pd-token -n configuration-anomaly-detection --from-literal=CAD_PD_TOKEN=${PD_TOKEN} --dry-run -oyaml > task-cad-checks-secrets-pd.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cad-pd-token
  namespace: configuration-anomaly-detection
type: Opaque
stringData:
  CAD_PD_TOKEN: CHANGEME
