---
apiVersion: v1
kind: Secret
metadata:
  name: cad-ocm-client-secret
type: Opaque
stringData:
  CAD_OCM_CLIENT_ID: CHANGEME
  CAD_OCM_CLIENT_SECRET: CHANGEME
  CAD_OCM_URL: "https://api.stage.openshift.com"
